### ISSUE TITLE
Need access to "report documentation bugs" in the Public Cloud drafts

### ISSUE THREAD

**Issue by kvanderveer** [SUSE/doc-public-cloud#2]
When I try to click on feedback, I am directed to this project: https://bugzilla.suse.com/enter_bug.cgi?&product=Product%20Name&component=Documentation&short_desc=%5Bdoc%5D%20Part%26nbsp%3BI%20%20Getting%20Started%20&comment=Part%26nbsp%3BI%20%20Getting%20Started%20%3A%0A%0Ahttps%3A%2F%2Fsusedoc.github.io%2Fdoc-public-cloud%2Fmain%2Fhtml%2Fpublic-cloud%2Fpart-one.html%23&assigned_to=assignee%40suse.com

But it says, Permission Denied: Sorry, either the product Product Name does not exist or you aren't authorized to enter a bug into it.

Other team members will want access to this also, we should think about how to add them.

**Comment by cjschroder** [comment]
Hi @kvanderveer, thanks for reporting this. It looks like the Documentation component is missing from the Product (for example, see  https://bugzilla.suse.com/enter_bug.cgi?product=SUSE%20Linux%20Enterprise%20Server%2015%20SP3%20in%20Public%20Clouds, there should be a Documentation option in the Components selector). We'll take care of it.

**Comment by cwickert** [comment]
@kvanderveer, I can get in touch with the Bugzilla-Admins, the question is what product, component and versions we want.

As you can see at https://bugzilla.suse.com/enter_bug.cgi?classification=SUSE%20Linux%20Enterprise%20Server most SLE products already have "... in Public Clouds" products, however they are version specific (e.g. "SUSE Linux Enterprise Server 15 SP3 in Public Clouds"). Our docs will never be versioned I guess because your processes to create the images are not either.

I suggest to use our "Documentation" product. At the moment it only has a "SmartDocs" component, but we could add "Public Cloud", too. Would that work for you?

**Comment by cwickert** [comment]
We now have the "Public Cloud" component in Bugzilla and I have updated the configuration accordingly.

**Comment by cwickert** [comment]
Verified it works now.

**Comment by cjschroder** [comment]
Cool, that was fast work! Thanks @cwickert!
